# Generated by Django 5.0.4 on 2024-06-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('firstName', models.CharField(db_column='first_name', max_length=50)),
                ('lastName', models.CharField(db_column='last_name', max_length=50)),
                ('email', models.CharField(db_column='user_email', max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
