# Generated by Django 5.0.4 on 2024-06-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='move_title', max_length=200)),
                ('file', models.BinaryField()),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
