# Generated by Django 5.0.4 on 2024-06-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_movie_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='file',
            field=models.BinaryField(editable=True),
        ),
    ]
