# Generated by Django 5.0.4 on 2024-06-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0003_alter_movie_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='A discription for the movie', max_length=2000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(db_column='movie_title', max_length=200),
        ),
    ]
