# Generated by Django 5.0.6 on 2024-06-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0004_movie_description_alter_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(default='A description for the movie', max_length=2000),
        ),
    ]
